extends:
  - '@enkidevs/eslint-config-backend'
rules:
  no-param-reassign: 'off'
  security/detect-non-literal-fs-filename: 'off' # because we use fs.readFileSync in tests
  jest/no-standalone-expect: 'warn' # because we're using jest-in-case
